### ISSUE TITLE
Why isn't this in core?

### ISSUE THREAD

**Issue by stevenvachon** [ehmicky/log-process-errors#17]
Shouldn't it be?

**Comment by ehmicky** [comment]
Thanks, that's a nice compliment!

I think it would go against the philosophy of Node.js being small though. However feel free to post an issue on Node.js GitHub repository if there is a particular feature that you think should be in core Node.js. If you do so, please mention @ehmicky in the post so I get notified.

Thanks again for your interest!

**Comment by ehmicky** [comment]
@all-contributors please add stevenvachon for this interesting question
