### ISSUE TITLE
Remove (seemingly) unused core-js dependency

### ISSUE THREAD

**Issue by oles** [ehmicky/log-process-errors#29]
**Which problem is this feature request solving?**

Would rather not involuntary use core-js

**Describe the solution you'd like**

Remove core-js from package.json and package-lock.json

**Describe alternatives you've considered**

Leaving it be, if log-process-errors uses it somehow I'm not seeing

**Can you submit a pull request?**

Yes.

Seeing I only get one result when searching for "core-js" (https://github.com/ehmicky/log-process-errors/search?q=core-js&unscoped_q=core-js) - is it perhaps not used anymore?

**Comment by ehmicky** [comment]
Fixed in [`6.0.1`](https://github.com/ehmicky/log-process-errors/releases/tag/6.0.1).

Please note `core-js` was indeed used in two instances: `Object.entries()` was used somewhere and `Array.prototype.flatMap()` was used somewhere else. I replaced both instances to be able to remove `core-js`.

**Comment by oles** [comment]
Awesome! Thanks, @ehmicky :tada:

**Comment by oles** [comment]
Would you look at that. You're the same person working on https://github.com/netlify/build
From your recent activity there, it seems this package will be updated there in due time.

Keep up the good work - really enjoying Netlify :heart:

**Comment by ehmicky** [comment]
For Netlify Build: issue opened in https://github.com/netlify/build/issues/1143

Removing it required a backport since Netlify Build cannot use the latest `log-process-errors` due to different Node.js version support. I did the backport in [`5.1.2`](https://github.com/ehmicky/log-process-errors/releases/tag/5.1.2).
