### ISSUE TITLE
5.1.0 marked as latest in npm

### ISSUE THREAD

**Issue by abrenneke** [ehmicky/log-process-errors#30]
Not sure how it happened, but 5.1.0 is marked as latest in npm, above 6.1.0, this caused `yarn upgrade --latest` to attempt to downgrade the package:

![image](https://user-images.githubusercontent.com/342540/78610228-41b33300-7819-11ea-8f54-778286dd99dc.png)

**Comment by ehmicky** [comment]
Thank you so much for reporting this! I just fixed it.
@all-contributors Could you please add @abrenneke for reporting this bug?
