### ISSUE TITLE
Why not raise the core console.log problems to node.js?

### ISSUE THREAD

**Issue by binarykitchen** [ehmicky/log-process-errors#39]
Fantastic, totally dig the idea. There is too much noise in `console.log` but why another new library? Raise this with the node.js core community and improve it there instead?

Sorry for the blunt question, but I feel like I have to ... Peace out :)

**Comment by ehmicky** [comment]
Hi @binarykitchen,

Thanks a lot for the compliment!

I agree with you that trying to contribute improvements upstream is often a good idea. In this instance, while some logic does feel like it belongs to userland, I can see how some could be suggested to core Node.js.

That being said, I do not currently have the time to make such a contribution to core Node.js. However, if you wanted to do so, please feel free to tag me, so I can follow the discussion. :+1:
